### ISSUE TITLE
PHP Warning:  exif_imagetype(): stream does not support seeking in 

### ISSUE THREAD

**Issue by dynamohuang** [mohuishou/ImageOCR#1]
what wrong with is?  Is some extension problem?
➜  image-ocr php study.php
PHP Warning:  exif_imagetype(): stream does not support seeking in /Users/dynamo/PhpstormProjects/hack/vendor/mohuishou/image-ocr/Image.php on line 40

Warning: exif_imagetype(): stream does not support seeking in /Users/dynamo/PhpstormProjects/hack/vendor/mohuishou/image-ocr/Image.php on line 40

**Comment by mohuishou** [comment]
Perhaps the image link is wrong.

Replace the image link, the program can be successfully run

**Comment by mohuishou** [comment]
https://github.com/mohuishou/ImageOCR/commit/b451f452459c8c55e6431adefcabfb25edda12cb
