### ISSUE TITLE
错误：请先获取分割后的图片

### ISSUE THREAD

**Issue by Jinnrry** [mohuishou/ImageOCR#10]
把示例代码改成我自己的图片以后出现错误提示“请先获取分割后的图片”，我看以前的Issues说设置灰度阈值，但是.........求作者加一个能够实时显示图像的函数啊，我改了灰度以后没法看到图片，不知道效果如何

**Comment by mohuishou** [comment]
https://github.com/mohuishou/ImageOCR/blob/master/src/ImageOCR.php#L180

这是报错的代码，说明图片没有被成功分割，实时显示图像可以尝试使用`ImageTool::drawBrowser($data)`这个函数进行点阵显示

**Comment by mohuishou** [comment]
对了，你可以把你的图片上传上来看看

**Comment by Jinnrry** [comment]
![getcaptcha](https://user-images.githubusercontent.com/19919556/31181987-40bca03e-a955-11e7-94d8-fb1016f2e438.gif)

**Comment by mohuishou** [comment]
经过测试的确是灰度设置的问题，导致二值化的时候直接把图片变成一个空白图形了，所以就相当于没有分割图形，我马上新增一个debug选项，使报错的时候可以显示当前步骤的二值化图像

**Comment by mohuishou** [comment]
d0ea94ce8ec7004e36a35929af022c033b5d34b5
