### ISSUE TITLE
how use setup.php?

### ISSUE THREAD

**Issue by cong520** [mohuishou/ImageOCR#11]
您好，请问！db数据库做哪里下呢？ 运行setup.php 也不行，这个链接http://www.169ol.com/Stream/Code/getCode也打不开呢？

**Comment by mohuishou** [comment]
请看最新的代码，example文件夹里面，可以直接运行`study.php`或者`index.php`

**Comment by mohuishou** [comment]
链接是以前用来测试的，现在无效了，最新的代码里面使用了自动生成的方法，应该没有这个错误

**Comment by cong520** [comment]
不太理解这个要怎么用，我把composer require mohuishou/image-ocr 生成的文件放在tp5的vendor,把image-ocr改名为ImageOCR。
控制器中        
public function index()
    {
vendor('Mohuishou.ImageOCR.Image');
$image=new \Mohuishou\ImageOCR\Image("http://auto.test.com/sss.png");
        $a=$image->find();
$code=implode("",$a);
echo "验证码：$code \n";}
然后报
致命错误: Class 'Mohuishou\ImageOCR\StorageFile' not found
        //从数据库中取出特征值
        $db=new StorageFile();

**Comment by cong520** [comment]
直接在根目录用composer require mohuishou/image-ocr，然后访问http://auto.testv.com/vendor/mohuishou/image-ocr/   
也会报路径错误，里面命名空间都是Mohuishou\ImageOCR\Example ，我要怎么来安装合适呢

**Comment by cong520** [comment]
可以给个步骤吗？放到TP5上或者直接在根目录，我下载example里面的文件。composer 后运行也是各种路径错误

**Comment by mohuishou** [comment]
不太清楚tp5的逻辑，你可以先git clone项目到本地，然后composer install，然后试试进入本地文件夹运行php -S localhost:8080，看看示例能不能运行，然后具体使用的时候可以参考example来写，因为每个验证码识别的参数和步骤都要进行一定的调整，所以具体逻辑需要自己完善

**Comment by cong520** [comment]
可以运行了，我再研究研究适配的。谢谢哈，开发这个好东西。 有些1个字母会变成几个数字 这个情况应该可以判断下位数

**Comment by mohuishou** [comment]
没事，这个具体的参数是要调整的
