### ISSUE TITLE
能识别那种数学计算的验证码吗

### ISSUE THREAD

**Issue by lkp186** [mohuishou/ImageOCR#12]

**Comment by mohuishou** [comment]
理论上是可以的，只要能把各个字符给识别出来，计算还是比较简单的

**Comment by lkp186** [comment]
我网找了很多，好像没有第三方提供服务，貌似只能用python了

**Comment by mohuishou** [comment]
第三方服务的话，最直接的应该就是各种打码平台了，不过应该也有简单的识别api，如果是php话，纯php写的还真没多少
