### ISSUE TITLE
无法安装，请求帮助

### ISSUE THREAD

**Issue by lvqing11** [mohuishou/ImageOCR#15]
不太清楚tp5的逻辑，你可以先git clone项目到本地，然后composer install，然后试试进入本地文件夹运行php -S localhost:8080，看看示例能不能运行，然后具体使用的时候可以参考example来写，因为每个验证码识别的参数和步骤都要进行一定的调整，所以具体逻辑需要自己完善
--

===================================================

按照上述指示，我在服务器上完成了 
git clone https://github.com/mohuishou/ImageOCR.git
然后
 cd ImageOCR/
然后
composer install
以上操作都能正常完成
然后
php -S localhost:8080
提示已经监听
Listening on http://localhost:8080
Document root is /var/www/html/ocr/ImageOCR

然后
wget http://localhost:8080
提示
404 Not Found

然后
wget http://localhost:8080/example
提示
 500 Internal Server Error

麻烦了

**Comment by mohuishou** [comment]
> 现在在外地，后天才能回去用电脑看看。

针对你遇到的问题，可能是下面的步骤有问题

- composer install 需要在example文件夹执行一下
- example 依赖sqlite3数据库，需要检查一下是否安装
- 服务启动需要在example文件夹
- 启动服务器之后访问localhost:8080/index.php试试

**Comment by lvqing11** [comment]
谢谢您的指导， 我再试试，麻烦了。 


在 2018-02-27 21:55:27，"Mo Huishou" <notifications@github.com> 写道：


现在在外地，后天才能回去用电脑看看。

针对你遇到的问题，可能是下面的步骤有问题

composer install 需要在example文件夹执行一下
example 依赖sqlite3数据库，需要检查一下是否安装
启动服务器之后访问localhost:8080/index.php试试

**Comment by mohuishou** [comment]
没事，如果没有问题了顺手关闭一下issue
