### ISSUE TITLE
composer 安装不了

### ISSUE THREAD

**Issue by xbw12138** [mohuishou/ImageOCR#16]
Loading composer repositories with package information
Updating dependencies (including require-dev)

**Comment by mohuishou** [comment]
不好意思，现在看到，直接clone下来吧，最新版没有push到composer

**Comment by mohuishou** [comment]
https://github.com/mohuishou/ImageOCR/commit/6b025e5a81b4b1ca2a1601d5309cc7e325a4d3f5
