### ISSUE TITLE
运行时出现这个问题

### ISSUE THREAD

**Issue by EternalSuno** [mohuishou/ImageOCR#17]
Warning: require_once(vendor/autoload.php): failed to open stream: No such file or directory 。
下载安装后没有这个文件啊

**Comment by mohuishou** [comment]
应该是composer的问题。需要使用composer

**Comment by waltkong** [comment]
too much error. 
Fatal error: Call to undefined function Mohuishou\ImageOCR\exif_imagetype() in E:\phpstudy2018\PHPTutorial\WWW\ceshi\Mohuishou\ImageOCR\src\Image.php on line 65

Parse error: syntax error, unexpected 'clone' (T_CLONE), expecting identifier (T_STRING) in E:\phpstudy2018\PHPTutorial\WWW\ceshi\Mohuishou\ImageOCR\example\Storage.php on line 19

**Comment by mohuishou** [comment]
https://github.com/mohuishou/ImageOCR/commit/6b025e5a81b4b1ca2a1601d5309cc7e325a4d3f5
