### ISSUE TITLE
运行时CaptchaBuilder类找不到

### ISSUE THREAD

**Issue by yisuixin** [mohuishou/ImageOCR#18]
运行时提示这个类找不到“Class 'Minho\Captcha\CaptchaBuilder' not found”

**Comment by mohuishou** [comment]
example里面需要运行composer install安装依赖

**Comment by mohuishou** [comment]
https://github.com/mohuishou/ImageOCR/commit/6b025e5a81b4b1ca2a1601d5309cc7e325a4d3f5
