### ISSUE TITLE
识别不了数字7

### ISSUE THREAD

**Issue by srayaa** [mohuishou/ImageOCR#19]
识别不了数字7,其它的数字准确率挺高
![1111](https://user-images.githubusercontent.com/13327908/51025614-8117b300-15c7-11e9-8ee7-1841ccdaebbd.png)
![test](https://user-images.githubusercontent.com/13327908/51025628-8a088480-15c7-11e9-87b1-90341c3fc054.png)
![2222](https://user-images.githubusercontent.com/13327908/51025721-c3d98b00-15c7-11e9-88d3-3378dca94339.png)

**Comment by mohuishou** [comment]
应该是数据库里面保存的数据的问题，如果之前保存的数据不够准确的话，识别率就会低一些，这个库没做识别上的优化
