### ISSUE TITLE
识别报错！

### ISSUE THREAD

**Issue by mkerj** [mohuishou/ImageOCR#22]
这种配置基本上都能识别出来，可就是报错
public function __construct($path)
    {
        $image=new Image($path);
        $this->image_ocr=new ImageOCR($image);

        //开启的debug模式
        $this->image_ocr->setDebug(true);
        //初始化
        $this->image_ocr->setMaxGrey(90);
        $this->image_ocr->setMinGrey(130); // 130  
        $this->image_ocr->setStandardWidth(130);
        $this->image_ocr->setStandardHeight(50);
    }
错误如下：

请先获取分割之后的图片
[2] ErrorException in OCR.php line 128
Invalid argument supplied for foreach()

**Comment by mohuishou** [comment]
有调用分割的API么，https://github.com/mohuishou/ImageOCR#%E5%88%86%E5%89%B2

**Comment by mohuishou** [comment]
给出的代码不全没有办法判断具体的错误

**Comment by mkerj** [comment]
public function __construct($path)
    {
        $image=new Image($path);
        $this->image_ocr=new ImageOCR($image);

        //开启的debug模式
        $this->image_ocr->setDebug(true);
        //初始化
        $this->image_ocr->setMaxGrey(90);
        $this->image_ocr->setMinGrey(25); // 130
        $this->image_ocr->setStandardWidth(65);
        $this->image_ocr->setStandardHeight(25);
    }

    public function standard()
    {
        //避免重复调用
        if (!empty($this->standard_data)) {
            return $this->standard_data;
        }

        try {
            //第一步灰度化
            $this->image_ocr->grey();
            //第二步二值化
            $this->image_ocr->hashByBackground(ImageOCR::MAX_MODEL);
            //下一步会用到连通域分割法，先初始化
            $this->image_ocr->setImageConnect();
            //第三部除噪&第四步分割
            $this->image_ocr->splitByConnect();
            //第五步标准化
            return $this->image_ocr->standard();
        } catch (\Exception $e) {
            echo $e->getMessage();
        }
        return false;
    }
所有代码用的是实例的 ，我只改了二值化和宽高。

**Comment by mohuishou** [comment]
我直接运行修改`docker`容器中的参数, 和你一致之后还是ok的，没有复现你的这个问题， 你有修改其他地方么。

```php
 public function __construct($path)
    {
        $image=new Image($path);
        $this->image_ocr=new ImageOCR($image);

        //开启的debug模式
        $this->image_ocr->setDebug(true);

        //初始化
        $this->image_ocr->setMaxGrey(90);
        $this->image_ocr->setMinGrey(25);
        $this->image_ocr->setStandardWidth(65);
        $this->image_ocr->setStandardHeight(25);
    }
```

**Comment by mkerj** [comment]
难道和图片有关？这里有 0-999个图片，您可以测试一下。http://cz.7q85.com/temp/img/1.png

**Comment by mkerj** [comment]
没有改其它的地方，我提供验证码给您，您方便测试一下：http://prw4hcq80.bkt.clouddn.com/1.png
这个地址 有 1-8个验证码。 http://prw4hcq80.bkt.clouddn.com/1...8.png

**Comment by mohuishou** [comment]
晚上帮你看下，现在有点忙

**Comment by mkerj** [comment]
好的，谢谢！~

**Comment by mohuishou** [comment]
我在`index.php`注释掉了生成图片的代码

```php
// $captch->create();
$img_path=__DIR__."/img/1.png";
// $captch->save($img_path,1);

$img=new \Mohuishou\ImageOCR\Example\OCR($img_path);
```

重启之后也没有报错
![image](https://user-images.githubusercontent.com/15172509/58187861-31ba5f80-7cea-11e9-903a-f83b45c55ba4.png)

**Comment by mkerj** [comment]
我测试的情况，当识别结果差不多正确的时候 就会报错，如果结果是错误的就能正常。

**Comment by mohuishou** [comment]
那只能怀疑是参数问题，除噪分割之后标准化之后没有数据了，这个建议你打断点debug一下，或者每一步都都把结果打印一下
