### ISSUE TITLE
写了个自动训练脚本训练了一晚上之后变成这样了

### ISSUE THREAD

**Issue by kasuganosoras** [mohuishou/ImageOCR#24]
![img](https://i.imgur.com/AIlWCUU.png)

就是生成验证码图片，然后将验证码文本作为输入内容提交给 OCR 进行学习
挂着运行了一晚上，训练了 97350 张图片，就变这样了……
db 文件已经 105MB 了

**Comment by kasuganosoras** [comment]
一开始训练了一千多张的时候挺准确的，十张里面六七张都正确，可不知道为啥越往后就越不准了，到现在没有一个对的……（挠头

**Comment by mohuishou** [comment]
这个只是一个很简单的库，识别的方法很原始，没有用到机器学习那一套，所以并不是越多越好，我测试的是几百张的效果就可以了
![image](https://user-images.githubusercontent.com/15172509/59359113-5beac480-8d60-11e9-91d0-ff7ca174b833.png)

**Comment by kasuganosoras** [comment]
好吧……我把原来的 db 文件删了让它重新训练了
另外有没有办法识别出 + - × ÷ 运算符号？我试了一下貌似识别不出来

**Comment by mohuishou** [comment]
运算符号没有试过，理论上是可以的，不过×和X太像了，准确率应该比较堪忧

**Comment by kasuganosoras** [comment]
能识别 + - 就可以了，例如这种
![img](https://i.imgur.com/W0lgsEG.png)
![img](https://i.imgur.com/U19FQRC.png)
左右都只有一位数字，中间一个运算符

**Comment by mohuishou** [comment]
这种还没有试过，可以尝试一下
