### ISSUE TITLE
出现"请先获取分割之后的图片" 的问题

### ISSUE THREAD

**Issue by thejoven** [mohuishou/ImageOCR#5]
![default](https://cloud.githubusercontent.com/assets/3352179/25690649/f67d0fb6-30c5-11e7-8301-b3d98b8dd039.jpg)
![validatecode](https://cloud.githubusercontent.com/assets/3352179/25690648/f6704330-30c5-11e7-95cf-decb70425452.jpg)

目前还不知道怎么解决

**Comment by mohuishou** [comment]
抱歉新版本还没有完善，最近没有太多的时间

**Comment by mohuishou** [comment]
你可以尝试一下原来的版本

**Comment by mohuishou** [comment]
fixed a78aa70ce124c22a3ac368b8cc594981d5817f65

出现这个原因是分割图片出错，一般是因为灰度阈值设置错误导致的，可以查看最新的example，谢谢
