### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Jinnrry** [mohuishou/ImageOCR#8]
我最近也需要一个php的验证码识别项目，我现在在测试您的代码，我发现Image的rgb2grey方法并不能达到转灰度图的效果，是我测试代码问题吗？建议在工具类中添加一个show方法，可以直接显示出某一步操作之后的图像，比如ImageTool::show($image->rgb2grey())这样可以直接显示出灰度图，另外，我测试时用于显示图像的代码
`        //计算图片的宽度与高度
        $img_w=count($array_data[0]);
        $img_h=count($array_data);

        //图像初始化
        $img = imagecreatetruecolor($img_w,$img_h);//创建一幅真彩色图像
        $white=imagecolorallocate($img, 255, 255, 255);//白色
        $black=imagecolorallocate($img, 0, 0, 0);//黑色

        //背景填充为白色
        imagefill($img, 0,0, $white);

        //进行画图
        for($h=0;$h<$img_h;$h++){
            for($w=0;$w<$img_w;$w++){
                imagesetpixel($img, $w,$h, $array_data[$h][$w]);
            }
        }

        return $img;`

**Comment by mohuishou** [comment]
`rgb2grey`这个方法是将本来的rgb值通过计算之后然后输出数组，并不是输出图像，因为后面的操作需要用到的还是数组而不是图像，输出这个函数可以添加，以前的版本是有的，如果你着急使用并且验证码字符等宽的话可以直接用tag0.1.1这个版本 https://github.com/mohuishou/ImageOCR/tree/0.1.1
当前版本还有些遗留问题还没有解决

**Comment by mohuishou** [comment]
这个方法可以在浏览器当中显示基本的点阵图
https://github.com/mohuishou/ImageOCR/blob/master/src/ImageTool.php#L59
